# Generated by Django 2.0.2 on 2019-04-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='votes_title',
            new_name='votes_total',
        ),
    ]
